_target_: src.models.dnam.fcmlp.FCMLPModel

n_input: 78394
topology: [512, 256, 128, 64]
n_output: 4
task: "classification"
dropout: 0.0
loss_type: "CrossEntropyLoss"
lr: 0.0001
weight_decay: 0.00005
