_target_: src.models.dnam.tabnet.TabNetModel

task: "classification"
input_dim: 391023
output_dim: 4
n_d_n_a: 8
n_steps: 3
gamma: 1.3
n_independent: 1
n_shared: 2
virtual_batch_size: 128
mask_type: "sparsemax"
loss_type: "CrossEntropyLoss"
optimizer_lr: 0.005
optimizer_weight_decay: 0.0
scheduler_step_size: 50
scheduler_gamma: 0.8
