# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: "mean_absolute_error"
optimized_mean: "cv_mean" # "cv_mean_val_test"

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null

    # name of the study to persist optimization results
    study_name: null

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: minimize

    # total number of runs that will be executed
    n_trials: 500

    # choose Optuna hyperparameter sampler
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: ${seed}
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 25
      n_ei_candidates: 5
      multivariate: false
      warn_independent_sampling: true

    # define range of hyperparameters
    # 'embed_dim' must be divisible by 'n_heads'
    params:
      widedeep_ft_transformer.optimizer_lr: tag(log, interval(0.00001, 1)) # tag(log, interval(0.001, 0.04)) tag(log, interval(0.00001, 1))
      widedeep_ft_transformer.optimizer_weight_decay: tag(log, interval(0.0000001, 0.001)) # tag(log, interval(0.00001, 0.001)) tag(log, interval(0.00000001, 0.1))
      widedeep_ft_transformer.embed_dim: choice(16, 32, 64, 128) # choice(32, 64, 128) choice(16, 32, 64)
      widedeep_ft_transformer.n_heads: choice(2, 4, 8, 16) #  choice(16, 32) choice(2, 4, 8, 16)
      widedeep_ft_transformer.n_blocks: choice(1, 2, 4, 8) # choice(6, 8) choice(2, 4, 6)
      widedeep_ft_transformer.attn_dropout: interval(0.0, 0.3)  # choice(0.2) choice(0.05, 0.1, 0.2)
      widedeep_ft_transformer.ff_dropout: interval(0.0, 0.3) # choice(0.1) choice(0.05, 0.1, 0.2)
      widedeep_ft_transformer.mlp_hidden_dims: choice([200, 100, 50, 1], [200, 100, 1], [100, 50, 1], [100, 1]) # choice([200, 100, 50, 1], [400, 200, 100, 1]) choice([200, 100, 1], [100, 50, 1], [200, 100, 50, 1])
      widedeep_ft_transformer.mlp_dropout: interval(0.0, 0.3) # choice(0.05) choice(0.05, 0.1, 0.15)
