# @package _global_

# specify here defaults
defaults:
  - _self_
  - experiment: immuno/age_inference        # Global parameters of experiment
  - datamodule: immuno/age                  # Information about dataset
  - trainer: null                           # Run configuration for DNN models
  - callbacks: null                         # Callbacks for DNN models
  - logger: none                            # Loggers for DNN models
  - hydra: default                          # Output paths for logs

  - model: immuno/age/widedeep_ft_transformer        # Model
  - hparams_search: null                    # Model-specific hyperparameters

  # Enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
