# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: "accuracy_weighted"

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null

    # name of the study to persist optimization results
    study_name: null

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # total number of runs that will be executed
    n_trials: 15

    # choose Optuna hyperparameter sampler
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: ${seed}
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 5
      n_ei_candidates: 5
      multivariate: false
      warn_independent_sampling: true

    # define range of hyperparameters
    params:
      tabnet.n_d_n_a: choice(8)
      tabnet.n_steps: choice(3)
      tabnet.gamma: choice(1.3)
      tabnet.n_independent: choice(1)
      tabnet.n_shared: choice(2)
      tabnet.optimizer_lr: choice(0.5, 0.1, 0.05, 0.01, 0.005, 0.001, 0.0005, 0.0001)
      tabnet.optimizer_weight_decay: choice(0.0)
      tabnet.scheduler_step_size: choice(10, 50, 100)
      tabnet.scheduler_gamma: choice(0.7, 0.9)

